array = list(input('배열 입력: '))
i,j,k = str(input('숫자 입력: ')).split( )
i = int(i)
j = int(j)
k = int(k)
#print(array, i, j, k)
li = list(array[i-1:j])
li.sort()
print(li)
print(li[k-1])
#print(array[i+k])